-- Afrilex Conseil — exécuter sur MySQL si la base existe déjà sans cette table
CREATE TABLE IF NOT EXISTS `job_applications` (
  `id`                       INT AUTO_INCREMENT PRIMARY KEY,
  `first_name`               VARCHAR(120)   NOT NULL,
  `last_name`                VARCHAR(120)   NOT NULL,
  `email`                    VARCHAR(200)   NOT NULL,
  `phone`                    VARCHAR(100)   DEFAULT NULL,
  `city_country`             VARCHAR(200)   DEFAULT NULL,
  `linkedin_url`             VARCHAR(500)   DEFAULT NULL,
  `position_applied`         VARCHAR(80)    NOT NULL,
  `contract_type`            VARCHAR(40)    NOT NULL,
  `availability`             VARCHAR(160)   DEFAULT NULL,
  `experience_years`         VARCHAR(24)    DEFAULT NULL,
  `education_level`          VARCHAR(48)    DEFAULT NULL,
  `languages`                VARCHAR(400)   DEFAULT NULL,
  `reference_offer`          VARCHAR(64)    DEFAULT NULL,
  `sought_role_title`        VARCHAR(255)   DEFAULT NULL,
  `application_mode`         VARCHAR(24)    DEFAULT NULL,
  `motivation`               TEXT           NOT NULL,
  `cv_original_name`         VARCHAR(255)   NOT NULL,
  `cv_stored_path`           VARCHAR(500)   NOT NULL,
  `locale`                   VARCHAR(8)     DEFAULT 'fr',
  `consent_data_processing`  TINYINT(1)     NOT NULL DEFAULT 0,
  `status`                   ENUM('nouveau','examine','entretien','refuse','embauche','archive')
                             NOT NULL DEFAULT 'nouveau',
  `created_at`               DATETIME       DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_job_app_email` (`email`),
  INDEX `idx_job_app_status` (`status`),
  INDEX `idx_job_app_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
